### ISSUE TITLE
Improve WM creation

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#496]
Fastest way to create WM.
- Map
- Create models
- Swipe models in with gui op iPad
- dump-ed
- round numbers; set everything straight

Current issue: dump-ed not working:
Desired output of dump_ed:
```
- type: "table_120x80x76"
      id: "dinner_table"
      pose:
          x: 0.4
          y: 1.92
          z: 0.0
```
Current output:
```
- type: "table"
      id: "dinner_table"
      pose:
          x: 0.4
          y: 1.92
          z: 0.0
```

In the ed_robocup plugin the type is inhered from parent type. This is unwanted an inconsistent with loading a WM in the default way. Because the inheriting is done in the ed model_loader, I don't want to change that one. A dirty fix is needed. This is done in tue-robotics/ed_robocup#5
A second fix is needed in ED, tue-robotics/ed#56. During processing the update requests, the type is retrieved from data of the update request. This is double because this is also done in the model_loader. Plus the plugin should have the authority to set the type, independent of the data. Therefore this should be removed.
