### ISSUE TITLE
Simulator SERGIO

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#577]
# Deliverable
- [ ] Working Simulator with working first stage challenges

# Steps:
- [ ] SSL
- [ ] Grasping
- [ ] Navigation
- [ ] Head

**Comment by LoyVanBeek** [comment]
In simulation, rosnode ```/sergio/head_ref``` publishes on ```/sergio/neck/references```. 
However, the rosnode ```sergio/fast_simulator``` only has an action_server ```/sergio/body/joint_trajectory_action```, which includes the ```neck_pan_joint, neck_tilt_joint```
This is one mismatch. 
There is another: sergio_description/custom/joint_groups.yaml defines
```yaml
    - name: head
      reference_topic: "/sergio/head/references"
      measurement_topic: "/sergio/head/measurements"
      joint_names:
          - neck_pan_joint
          - neck_tilt_joint
```
so the neck joints are expected on /sergio/head/references while ```/sergio/head_ref``` publishes on ```/sergio/neck/references```.
