### ISSUE TITLE
SERGIOs torso sends NANs as position to /sergio/joint_states

### ISSUE THREAD

**Issue by JosjaG** [tue-robotics/tue_robocup#607]
```rostopic echo /sergio/joint_states | grep nan``` outputs:
``` 
---
header: 
--
  stamp: 
    secs: 1526124306
    nsecs: 306253991
  frame_id: ''
name: [ankle_joint, knee_joint, hip_joint]
position: [nan, nan, nan]
velocity: [0.0, 0.0, 0.0]
effort: [0.0, 0.0, 0.0]
---
``` 
This breaks everything... :-1:
