### ISSUE TITLE
EdEntity.volumes broken

### ISSUE THREAD

**Issue by KevinDang74** [tue-robotics/tue_robocup#724]
World_model_ed used the entity.data attribute to parse the volumes (e.g. `on_top_of`) of an entity from.
But for (some?) entities, this attribute is empty and has it's volumes encoded in a separate, dedicated attribute:

```yaml
[id: "trashbin"
type: ''
types: []
existence_probability: 1.0
last_update_time: 
  secs: 0
  nsecs:         0
creation_time: 
  secs: 0
  nsecs:         0
has_shape: True
has_pose: True
pose: 
  position: 
    x: 2.99237614478
    y: 3.62256310813
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.336030446182
    w: 0.941851123712
data: '' # Empty
flags: []
convex_hull: 
  - 
    x: 0.15000000596
    y: 6.94901928e-06
    z: 0.0
  - much: 'more'
z_min: 0.0
z_max: 0.300000011921
volumes: #not empty!
  - 
    name: "on_top_of"
    subvolumes: 
      - 
        center_point: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs:         0
            frame_id: "/trashbin"
          point: 
            x: 0.0
            y: 0.0
            z: 0.4
        geometry: 
          type: 1
          dimensions: [0.4, 0.2, 0.30000000000000004]]
```
