### ISSUE TITLE
HERO2 Battery capacity

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#811]
To Track the battery capacity of HERO2 over time

**Comment by MatthijsBurgh** [comment]
```
header: 
  seq: 263
  stamp: 
    secs: 1557408140
    nsecs:         0
  frame_id: ''
voltage: 16.6189994812
current: -0.0143999997526
charge: 60.1343994141
capacity: 61.2000007629
design_capacity: 79.34400177
percentage: 0.980000019073
power_supply_status: 4
power_supply_health: 0
power_supply_technology: 2
present: True
cell_voltage: []
location: ''
serial_number: ''
```

**Comment by MatthijsBurgh** [comment]
2019-08-27
```
header: 
  seq: 1
  stamp: 
    secs: 1566931710
    nsecs:         0
  frame_id: ''
voltage: 13.984000206
current: -0.0
charge: 0.0
capacity: 68.6447982788
design_capacity: 79.34400177
percentage: 0.0
power_supply_status: 1
power_supply_health: 0
power_supply_technology: 2
present: True
cell_voltage: []
location: ''
serial_number: ''
```

**Comment by MatthijsBurgh** [comment]
2019-11-19
```
header: 
  seq: 1
  stamp: 
    secs: 1574191874
    nsecs:         0
  frame_id: ''
voltage: 15.9479999542
current: -35.0208015442
charge: 50.4720001221
capacity: 78.3359985352
design_capacity: 79.34400177
percentage: 0.639999985695
power_supply_status: 1
power_supply_health: 0
power_supply_technology: 2
present: True
cell_voltage: []
location: ''
serial_number: ''
```
