### ISSUE TITLE
modified file on sergio1, should we keep this? I reverted it. put it back and check it in if we still need this

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/tue_robocup#9]
waypoint(robotics_testlabs, _, exit_rips, pose_2d(-1.000,  0.000,  3.14)).   % in rips, exit could be different kind of exit

**Comment by Rayman** [comment]
Was this in `tue_knowledge/prolog/locations.pl`?

If that's the case, that file is obsolete and the change didn't matter. The new locations are given in `ed_object_models/models/robotics_testlabs/model.yaml`.

Snippet of `exit_1_rips`:
```yaml
 - type: "waypoint"
      id: "exit_1_rips"
      pose: { x: -1.480, y: -0.031, z: 0, rz: 3.1415 }
```
